leftnav:
- identifier: 239c8e43-8869-3770-b728-93953d2e52c5
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 5b76e9b4-dd73-5241-bbad-d2691b02db55
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: d9e0538f-c14c-28ac-90f7-878c60e90a9b
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: eeeb66a9-5f4b-2b56-ce9d-282babc3aea3
  name: Assignments
  pageRef: /pages/assignments/
  weight: 40
- identifier: 7ca62c52-b610-4286-d4d1-b8e2c54b4c6e
  name: Projects
  pageRef: /pages/projects/
  weight: 50
